#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

if [[ -z ${RUN_ON_START} ]]; then
    echo "[init-first-time] Env var not set. Ignoring."
else
    echo "[init-first-time] Backing up now"
    sh /config/restic_backup.sh
fi