---
kind: pipeline
type: docker
name: default

steps:
  - name: "Build Docker image"
    image: plugins/docker
    settings:
      registry: registry.digitalocean.com
      repo: theredkingdom/docker-restic-cron
      tags: latest
      username:
        from_secret: docker_do_username
      password:
        from_secret: docker_do_password
