---
kind: pipeline
type: docker
name: default

steps:
  - name: docker_push
    image: plugins/docker
    when:
      branch: master
      event: push
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.ethancotterell.co.uk/ethan/docker-restic-cron
      registry: registry.ethancotterell.co.uk
      tags: latest
