version: "3.3"

services:
  restic:
    image: restic
    container_name: restic
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - RESTIC_HOSTNAME=myserver  # otherwise defaults to a docker hostname
      - RESTIC_OPTIONAL_ARGS=
      - RESTIC_OPTIONAL_BACKUP_ARGS=
      - RESTIC_PASSWORD=your-super-secure-password
      # The values will determine the remote location. More information on backup targets can be found here:
      # https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html
      - RESTIC_REPOSITORY=
      - B2_ACCOUNT_ID=
      - B2_ACCOUNT_KEY=
    devices:
      - /dev/fuse
    volumes:
      - ./data:/data:ro
      - ./config:/config
